### ISSUE TITLE
[Bug] blank page at the end of every chapter from MangaPlus

### ISSUE THREAD

**Issue by hyoretsu** [TheNetsky/community-extensions#10]
First, thank you so much for bringing this to 0.8. It’s totally usable and fine if it’s hard to fix this (without resorting to potentially harmful workarounds, like simply trimming the last page)

**Comment by hyoretsu** [comment]
It’s happening on Dandadan chapters btw. I also got three blank pages at the end of illustration 3 on Yumeochi.

**Comment by henderea** [comment]
Ya, I'm seeing this too.

**Comment by TheNetsky** [comment]
Won't fix, feel free to make PR.
