### ISSUE TITLE
Nothing from Nhentai works

### ISSUE THREAD

**Issue by hyoretsu** [TheNetsky/community-extensions#11]
Title. Nothing shows up in Discover nor on Search, even though it throws a Cloudflare error.

**Comment by TheNetsky** [comment]
Then do the CF bypass?

**Comment by hyoretsu** [comment]
I forgot to clarify, that’s the only thing that seems to be working. Even after doing it, nothing shows up even after restarting the app.

**Comment by TheNetsky** [comment]
If it persists after correctly doing the CF bypass, consider it broken IG.

**Comment by hyoretsu** [comment]
Seems like I was hiding too many tags.
