### ISSUE TITLE
MangaNato source is broken

### ISSUE THREAD

**Issue by Tremayah** [TheNetsky/community-extensions#17]
[28-09.Paperback.txt](https://github.com/TheNetsky/community-extensions/files/12748963/28-09.Paperback.txt)
^logs

![8E82ED48-0540-45D0-BCF5-B04E5C04C37C](https://github.com/TheNetsky/community-extensions/assets/125309136/64bb6bee-9d8b-470f-a074-6fe4dc4bd897)

**Comment by TheNetsky** [comment]
Reinstall app.
