### ISSUE TITLE
Bato.to is using v2.5 instead of v3

### ISSUE THREAD

**Issue by macarenomarco** [TheNetsky/community-extensions#22]
Logs: 
[INFO] [2024-01-05T08:52:24.364Z] [AsyncOperation:start():51] [AsyncOperation] RequestOperation - https://bato.to

Device: iPad Air iOS 17.2

# Steps

1. Having added the community extensions repo, add bato.to as a source.
2. Search for manga using the keyword “Yamada”

# Expected result
It should display the results from the latest version (v3) of the site

# Actual result
It only displays the result for the previous version of the site: v2.5

# Proposal

Update the base URL to version 3 of the site.

**Comment by TheNetsky** [comment]
Updating the URL would break the source since the layout is different. It's not as easy as "updating the URL".

**Comment by macarenomarco** [comment]
Thanks! Wasn’t aware of the complexity behind the change. Is there a contributing guide? I’d like to look into the correct way to help with this.

**Comment by niclimcy** [comment]
I will update the source when v3 becomes the default, currently it seems like the site still defaults to v2
