### ISSUE TITLE
images from bato.to aren’t loading.

### ISSUE THREAD

**Issue by aissymy** [TheNetsky/community-extensions#3]
after exiting then come back to read, images from bato.to aren’t loading.
![7A851492-13BD-47DE-B1E3-8369FFB55563](https://user-images.githubusercontent.com/132310400/235545590-8bf78914-e76d-49b2-b2de-b7aa72f96d6c.jpeg)

**Comment by niclimcy** [comment]
BatoTo isnt even released yet? Are you using one of my older versions?
