### ISSUE TITLE
@ Paperback: JSError Error [PaperbackError(300)] JSError Error: Couldn't find any chapters for mangald: 156453! - parseChapterList@:2149:28

### ISSUE THREAD

**Issue by kratoscortez** [TheNetsky/community-extensions#33]
Bug description: AsuraScans is giving similar errors when opening any saved manwhas, as well as showing this blank screen when trying to view its home page in paperback. Clicking the cloud button on its homepage opens the webpage fine.

Expected behavior: view its homepage and read bookmarked content.
![IMG_4198](https://github.com/TheNetsky/community-extensions/assets/161261402/52b67d85-df5c-4f63-ad9b-fbc82c2e35f4)
![IMG_4199](https://github.com/TheNetsky/community-extensions/assets/161261402/b077353e-c972-4584-9cdb-a981ac802a10)

**Comment by TheNetsky** [comment]
Wrong repo
