### ISSUE TITLE
Edoujin source needs to be updated 

### ISSUE THREAD

**Issue by kratoscortez** [TheNetsky/community-extensions#37]
Edoujin is redirecting to https://ehentaimanga.com/ and needs to be updated

**Comment by TheNetsky** [comment]
Already done

**Comment by kratoscortez** [comment]
Hey I started getting this issue after the source issue and I have tried removing the extension and re-adding it but still occurs is there another reason it could be happening?
![image](https://github.com/TheNetsky/community-extensions/assets/161261402/828043fd-8c13-412a-a014-199ae9559e7d)

**Comment by TheNetsky** [comment]
Issue on your end, works fine for me.
