### ISSUE TITLE
Log_Error Issue

### ISSUE THREAD

**Issue by Cirashi** [TheNetsky/community-extensions#38]
Hi! I apologize for the inconvenience, but I'm encountering an issue with MangaFreak (the problem concerns only this source) and haven't been able to find a solution on my own :( Furthermore, the issue doesn't concern just the first page or only that manga, but any page of any manga :( I searched the forum but couldn't find anything. I just hope I'm not wasting your time. Thank you in advance.

Log Files:
[16-03.Paperback.txt](https://github.com/TheNetsky/community-extensions/files/14624810/16-03.Paperback.txt)

Video:
https://github.com/TheNetsky/community-extensions/assets/133535007/2515eca8-005a-48d9-9d38-d859c6f27454

Additional Info: Already attempted to reinstall the app and extensions (using and not using backups), as well as logging out/in.

App Version: v0.8.7-r12

Source With Source Version: MangaFreak 2.0.2

**Comment by TheNetsky** [comment]
Wrong repo

**Comment by Cirashi** [comment]
I'm sorry, where should I post it?

**Comment by TheNetsky** [comment]
https://github.com/xOnlyFadi/xonlyfadi-extensions
