### ISSUE TITLE
BatoTo chapter titles

### ISSUE THREAD

**Issue by sinspirel** [TheNetsky/community-extensions#39]
Hi, just wanted to ask — if it's not too much trouble — whether it's possible to get chapter titles back for the Bato source? It used to have them, but I guess it was removed at some point? Unsure if it was purposely removed or not.

It's not a big deal, though. Just something that was nice and convenient to have.

**Comment by TheNetsky** [comment]
Uhm? Where does it not have them, it has them for me.

**Comment by sinspirel** [comment]
> Uhm? Where does it not have them, it has them for me.

These are the ones I've noticed. 

![bato](https://github.com/TheNetsky/community-extensions/assets/163821925/91d29065-38e6-4c27-9127-881d5ed3db34)

Looking back, not as many titles are affected as I thought. I think only those with the chapter title that have a space before the colon? So probably not even worth the fix lol. I think they stuck out to me so much because I have a handful of titles with that issue in my library, but at least the problem seems to be very much in the minority. 

Sorry about that, and thanks for checking. orz

**Comment by TheNetsky** [comment]
Seems like not worth effort as most of them indeed not have titles, It's cleaner for it to be consistent instead.
