### ISSUE TITLE
Bato.to not working. paperback: JSError Error [PaperbackError(300)] JSError Error: AsyncOperationTimedOutError - undefined:undefined:undefined

### ISSUE THREAD

**Issue by omi-kun** [TheNetsky/community-extensions#40]
Not working at all. Latest source repo (0.8) . I’m using MangaDex of the same repo and it’s working fine. Only Bato.to not working since the 0.7 repo.
![IMG_0915](https://github.com/TheNetsky/community-extensions/assets/69520027/4f5d194b-9b83-4b34-84a6-74e804fb4961)
Paperback v0.8.8-r3

**Comment by niclimcy** [comment]
No version number provided

**Comment by omi-kun** [comment]
Paperback v0.8.8-r3

**Comment by niclimcy** [comment]
source version.

**Comment by omi-kun** [comment]
BatoTo 3.1.2 from the Pb community extensions (0.8)

**Comment by niclimcy** [comment]
Click on the cloudflare icon to bypass cloudflare

**Comment by omi-kun** [comment]
okay so it seems like it wasn't working bc I didn't have the VPN on and BatoTo is not accessible in my country. Problem solved. Thanks
