### ISSUE TITLE
Chapters not loading

### ISSUE THREAD

**Issue by pattypaige** [TheNetsky/community-extensions#43]
![image](https://github.com/TheNetsky/community-extensions/assets/158430963/628d20e6-c9c5-4ce2-8c77-ac661b3f9c37) 

![image](https://github.com/TheNetsky/community-extensions/assets/158430963/9b5831b7-247e-4369-b295-c5ed810aa6ba)

Idk if it's the app itself or the extensions, but i need advice on how to fix this. Do i need to uninstall-install? I worry about my library and my extensions will be gone. I have a lot of manhwa's in my library.

**Comment by TheNetsky** [comment]
No loading where? Who? What? 

Make a backup, reinstall, load backup

**Comment by pattypaige** [comment]
Oh no, i did not create a back up :(( i thought logging in to my email is all good :(( is there anything i can do to fix this :((

**Comment by TheNetsky** [comment]
Sadly if you already deleted the app it's too late for that. The account does not store anything.

**Comment by pattypaige** [comment]
> Sadly if you already deleted the app it's too late for that. The account does not store anything.

It's okay. Good thing is, my paper back is now working. Also, i will have the chance to re-organized my library. Sadly I don't remember everything, but i think i will be able to restore or remember everything i like with the help of recommendations in reddit 🤷🏻‍♀️

**Comment by TheNetsky** [comment]
Well, always make a backup before removing the app!
