### ISSUE TITLE
Paperback:Processing imagefailed. Processor:WebPProcessor

### ISSUE THREAD

**Issue by j710328466** [TheNetsky/community-extensions#44]
## problem
here is the shortcut, and I record it, my book is xxx.pdf, What happened below: 
![微信图片_20240422135249](https://github.com/TheNetsky/community-extensions/assets/21166338/2346aeec-c3e8-427a-8cc0-613df49a146c)

https://github.com/TheNetsky/community-extensions/assets/21166338/2fe3baf1-e1d1-4423-b48a-b312859681fd

But everything is okay when I open it in the Chrome browser.

## expect

I can load my book as usual.
thanks

**Comment by TheNetsky** [comment]
Not a source from this repo

**Comment by Ivanmatthew** [comment]
> ## problem
> here is the shortcut, and I record it, my book is xxx.pdf, What happened below: ![微信图片_20240422135249](https://private-user-images.githubusercontent.com/21166338/324343161-2346aeec-c3e8-427a-8cc0-613df49a146c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODg4OTEsIm5iZiI6MTcxMzc4ODU5MSwicGF0aCI6Ii8yMTE2NjMzOC8zMjQzNDMxNjEtMjM0NmFlZWMtYzNlOC00MjdhLThjYzAtNjEzZGY0OWExNDZjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDEyMjMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMjYxODUyN2Y3ODAzZDU4MjYyZDk4OGJlNWY5ZWYzYWQxNDBlMTY1OGM4YjdkNjJkYzMzNDI2NzIxMjM2MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m7sRPv0-SaDXB0HQv29IOoFjHt_ipO5h3aEnLHycdVo)
> 
>  WeChat_20240422135258.mp4 
> 
> But everything is okay when I open it in the Chrome browser.
> 
> ## expect
> I can load my book as usual. thanks

Unless you converted the pdf to images, paperback app can not display them.
I believe you’re using self-hosted komga, right?
You need to provide images. To the paperback app, not PDFs.
