### ISSUE TITLE
Bato.to not working

### ISSUE THREAD

**Issue by pattypaige** [TheNetsky/community-extensions#49]
Idk if my net or unstable, but I can't read in manhwas in bato rn. ![image](https://github.com/TheNetsky/community-extensions/assets/158430963/50562d82-1bb4-4179-badf-4f2a11a445c3)

![image](https://github.com/TheNetsky/community-extensions/assets/158430963/2b973e52-e3ad-42ef-a5ff-c94da0d9b82e)

I even changed the dns of our wifi, because I thought that was the reason.

**Comment by TheNetsky** [comment]
site is down

**Comment by pattypaige** [comment]
I just checked it, you're right. I hope it won't turn out like mangakakalot where all of the chapters were gone 😭

![image](https://github.com/TheNetsky/community-extensions/assets/158430963/c40e6d3c-764e-436a-8b3e-8ae332a679e5)
