### ISSUE TITLE
AsuraScans not working

### ISSUE THREAD

**Issue by zeta556** [TheNetsky/community-extensions#53]
the list of manga is not loading. opening a chapter will not load the images

opening the cloudflare will open the site without a cludflare prompt

tried reinstalling the plugin, use different network, vpns

![IMG_9035](https://github.com/user-attachments/assets/4d0a95a6-6def-4c51-8fa6-0c9f4e3eb518)

**Comment by TheNetsky** [comment]
Reinstall app
