### ISSUE TITLE
TempleScan Paperback: JSError request not found

### ISSUE THREAD

**Issue by pdumrauf** [TheNetsky/community-extensions#55]
![image](https://github.com/user-attachments/assets/f63f7216-3a8d-43b8-b5c1-c064ef21f16b)

**Comment by TheNetsky** [comment]
Wrong repo

**Comment by pdumrauf** [comment]
Which is the repo? Thanks

**Comment by TheNetsky** [comment]
It'll say so wherever u got it from, also that source had been removed since it was broken.
