### ISSUE TITLE
Readcomiconline.li Returning Error

### ISSUE THREAD

**Issue by Ricahdoh** [TheNetsky/community-extensions#56]
Currently on Paperback v0.8.7-r12

Using xOnlyFadi's Extensions (0.8), have tried the 0.6 extension but the sources are made for 0.7 so that also didn't work. 

![IMG_9885](https://github.com/user-attachments/assets/0ad1eab8-a1bf-41f8-9827-3090fee13ca3)

**Comment by Ricahdoh** [comment]
Saw that another ticket about this was closed with the response "wrong repo." 

Which one should we be using?

**Comment by MaosyBaos** [comment]
The source doesn’t work as the source developer isn’t able to fix it due to not having access to his computer. Use another source in the meantime. Please do not ask what source.

**Comment by TheNetsky** [comment]
> Saw that another ticket about this was closed with the response "wrong repo."
> 
> Which one should we be using?

Where ever it says the source is from, which is not this one.
