### ISSUE TITLE
NHentai homepage section IDs incorrectly defined

### ISSUE THREAD

**Issue by yetiam-on-git** [TheNetsky/community-extensions#6]
In the source for nhentai, the homepage section IDs are generated  in getHomePageSections using outdated terms. id: 'new' should be id: 'date', 'popularToday' should be 'popular-today', 'popularWeekly' should be 'popular-week', and 'popularAlltime' should be 'popular'. The homepage is still generated correctly (separately), but the getMoreViewItems function does not sort properly and defaults to sorting by date in every section. Simple bug, simple fix 👍

**Comment by TheNetsky** [comment]
Fixed
