### ISSUE TITLE
mangareader.to wont load any chapters and cant access clouflare

### ISSUE THREAD

**Issue by koiinnano** [TheNetsky/community-extensions#64]
every time i try ti read something from mangareaderto it just loads for a while then prompts me a giant error log. When i tried to see if it was a problem with the cloudflare it would prompt me with another error log when i would click on the button.
![IMG_2821](https://github.com/user-attachments/assets/ebb39956-1826-454e-84ad-f9718a0b549b)
![IMG_2820](https://github.com/user-attachments/assets/ac2fb20d-3b9c-41b8-9c00-0c79913462d1)

**Comment by TheNetsky** [comment]
Wrong repo
