### ISSUE TITLE
MangaDex Not loading/downloading 

### ISSUE THREAD

**Issue by ItsNich** [TheNetsky/community-extensions#7]
Ive recently updated my paperback app to 8.0 and ever since, manga dex has not been working. I keep getting this error to retry. Ive tried everything I can think of to fix this error but nothing is working. Other sources seem to be working ok.

![40364E26-5850-49F0-B5B6-BF763195EAC3](https://github.com/TheNetsky/community-extensions/assets/140280364/1f59037b-fb5d-4ecb-8d40-988b6f22b468)

[22-07.Paperback.txt](https://github.com/TheNetsky/community-extensions/files/12137221/22-07.Paperback.txt)

**Comment by TheNetsky** [comment]
Likely dont have the source installed.

**Comment by TheNetsky** [comment]
Besides that no useful info given.

**Comment by ItsNich** [comment]
I believe i do have the source installed. What information would you need.

**Comment by ItsNich** [comment]
I did everything the same way for 0.8 as i did for the prior version. Added the source repo the same way and everything. I dont really know what you mean by not having the source installed.
![797D1BBB-E4F7-4637-AE20-BC767AE9436A](https://github.com/TheNetsky/community-extensions/assets/140280364/2b1a7402-9582-45d6-8d24-673051dcbc51)

**Comment by ItsNich** [comment]
I exported the error logs heres the file 
[Uploading 22-07.Paperback.txt…]()

**Comment by TheNetsky** [comment]
Likely slow internet or being rate limited by MangaDex.
